name: run main.py

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v6 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9' # install the python version needed

      - name: Installed package list
        run: apt list --installed

      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable

      - name: Remove default Chromium
        run: sudo apt purge chromium-browser

      - name: Install Google Chrome 114
        run: |
          wget --no-verbose -O /tmp/chrome.deb https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
          sudo apt install -y /tmp/chrome.deb
          google-chrome --version
          
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
        
      # - name: install python packages
        # run: |
          # python -m pip install --upgrade pip
          # pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          SIX_FIFTY_EIGHT_1: ${{ secrets.SIX_FIFTY_EIGHT_1 }}
          SIX_FIFTY_EIGHT_2: ${{ secrets.SIX_FIFTY_EIGHT_2 }}
          SIX_FIFTY_EIGHT_3: ${{ secrets.SIX_FIFTY_EIGHT_3 }}
          SIX_FIFTY_EIGHT_4: ${{ secrets.SIX_FIFTY_EIGHT_4 }}
          SIX_FIFTY_FIVE_1: ${{ secrets.SIX_FIFTY_FIVE_1 }}
          SIX_FIFTY_FIVE_2: ${{ secrets.SIX_FIFTY_FIVE_2 }}
          SIX_FIFTY_FIVE_3: ${{ secrets.SIX_FIFTY_FIVE_3 }}
          SIX_FIFTY_FIVE_4: ${{ secrets.SIX_FIFTY_FIVE_4 }}
          SIX_FORTY_NINE_1: ${{ secrets.SIX_FORTY_NINE_1 }}
          SIX_FORTY_NINE_2: ${{ secrets.SIX_FORTY_NINE_2 }}
          SIX_FORTY_NINE_3: ${{ secrets.SIX_FORTY_NINE_3 }}
          SIX_FORTY_NINE_4: ${{ secrets.SIX_FORTY_NINE_4 }}
          SIX_FORTY_FIVE_1: ${{ secrets.SIX_FORTY_FIVE_1 }}
          SIX_FORTY_FIVE_2: ${{ secrets.SIX_FORTY_FIVE_2 }}
          SIX_FORTY_FIVE_3: ${{ secrets.SIX_FORTY_FIVE_3 }}
          SIX_FORTY_FIVE_4: ${{ secrets.SIX_FORTY_FIVE_4 }}
        run: python main.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        run: git push